### ISSUE TITLE
Error after signing up new user

### ISSUE THREAD

**Issue by leonstafford** [leonstafford/sleepbus_org#5]
### Background

When trying to sign up as a new user, a server error is shown to the user

### Steps to reproduce

1. visit `/signup`
2. enter required fields and submit

### Expected results

 - user is shown sign up confirmation and is logged in 
 - user receives `Thank you for signing up` email

### Actual results

 - user receives errors:
 - user receives `Thank you for signing up` email but body is empty

```
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: emailTemplate

Filename: core/MY_Controller.php

Line Number: 588

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/sleepbus/public_html/system/core/Exceptions.php:272)

Filename: core/MY_Controller.php

Line Number: 160
```

**Comment by alexandruchircu** [comment]
With commit 0c38080a5e6fa5e7658093c8bb3978fad3f96141, a new user can be created; however, I cannot test the new user email - can the docker container send out mails?

**Comment by leonstafford** [comment]
OK, great! 

No, I don't believe it can and haven't looked into that yet. I'll try to get a new test server up for us today (current VPS offering is severely basic). I'll create a new task for local dev email testing now.

**Comment by leonstafford** [comment]
New issue for [local mail deliverability](https://github.com/leonstafford/sleepbus_org/issues/7)

**Comment by leonstafford** [comment]
Will code review this and do a *manual* deploy to current test server else deploy to new test server if I can get one up today

**Comment by leonstafford** [comment]
@alexandruchircu - this has been singularly tested on test.sleepbus.org and again after manual deploy to production site. :+1:
